name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build (Go ${{ matrix.go }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [stable]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Show versions
        run: go version

      - name: Install Go dependencies
        run: go mod download

      - name: Run go build
        run: go build ./...

      - name: Run go vet
        run: go vet ./...

  golangci-lint:
    name: Golang-CI (lint)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          only-new-issues: false
